// Generated by gencpp from file pulson_ros/EchoedRangeMeasurement.msg
// DO NOT EDIT!


#ifndef PULSON_ROS_MESSAGE_ECHOEDRANGEMEASUREMENT_H
#define PULSON_ROS_MESSAGE_ECHOEDRANGEMEASUREMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pulson_ros
{
template <class ContainerAllocator>
struct EchoedRangeMeasurement_
{
  typedef EchoedRangeMeasurement_<ContainerAllocator> Type;

  EchoedRangeMeasurement_()
    : header()
    , message_id(0)
    , requester_id(0)
    , responder_id(0)
    , precision_range(0)
    , precision_range_error(0)
    , timestamp(0)  {
    }
  EchoedRangeMeasurement_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , message_id(0)
    , requester_id(0)
    , responder_id(0)
    , precision_range(0)
    , precision_range_error(0)
    , timestamp(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _message_id_type;
  _message_id_type message_id;

   typedef uint32_t _requester_id_type;
  _requester_id_type requester_id;

   typedef uint32_t _responder_id_type;
  _responder_id_type responder_id;

   typedef uint32_t _precision_range_type;
  _precision_range_type precision_range;

   typedef uint16_t _precision_range_error_type;
  _precision_range_error_type precision_range_error;

   typedef uint32_t _timestamp_type;
  _timestamp_type timestamp;




  typedef boost::shared_ptr< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> const> ConstPtr;

}; // struct EchoedRangeMeasurement_

typedef ::pulson_ros::EchoedRangeMeasurement_<std::allocator<void> > EchoedRangeMeasurement;

typedef boost::shared_ptr< ::pulson_ros::EchoedRangeMeasurement > EchoedRangeMeasurementPtr;
typedef boost::shared_ptr< ::pulson_ros::EchoedRangeMeasurement const> EchoedRangeMeasurementConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pulson_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'pulson_ros': ['/home/robond/catkin_ws/src/pulson_ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e6826463afd1ec35691a83318a58e78";
  }

  static const char* value(const ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e6826463afd1ec3ULL;
  static const uint64_t static_value2 = 0x5691a83318a58e78ULL;
};

template<class ContainerAllocator>
struct DataType< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pulson_ros/EchoedRangeMeasurement";
  }

  static const char* value(const ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
uint16 message_id\n\
\n\
uint32 requester_id\n\
uint32 responder_id\n\
\n\
uint32 precision_range\n\
uint16 precision_range_error\n\
\n\
uint32 timestamp\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.message_id);
      stream.next(m.requester_id);
      stream.next(m.responder_id);
      stream.next(m.precision_range);
      stream.next(m.precision_range_error);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EchoedRangeMeasurement_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pulson_ros::EchoedRangeMeasurement_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "message_id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.message_id);
    s << indent << "requester_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.requester_id);
    s << indent << "responder_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.responder_id);
    s << indent << "precision_range: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.precision_range);
    s << indent << "precision_range_error: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.precision_range_error);
    s << indent << "timestamp: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PULSON_ROS_MESSAGE_ECHOEDRANGEMEASUREMENT_H
