# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pulson_ros/RangeNetNDB.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import pulson_ros.msg
import std_msgs.msg

class RangeNetNDB(genpy.Message):
  _md5sum = "e383cdc325496d8c4ee7600a42ab6f0e"
  _type = "pulson_ros/RangeNetNDB"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

uint32 host_node
uint16 message_id
uint8 number_of_neighbor_entries

pulson_ros/RangeNetNDBEntry[] database

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: pulson_ros/RangeNetNDBEntry
uint32 node_id

uint8 range_status
uint8 antenna_mode

uint16 stopwatch_time

uint32 range
uint16 range_error

uint16 range_velocity

uint8 range_measurement_type

uint8 flags

uint32 stats_age_ms

uint32 range_update_timestamp_ms
uint32 last_heard_timestamp_ms
uint32 added_to_ndb_timestamp_ms
"""
  __slots__ = ['header','host_node','message_id','number_of_neighbor_entries','database']
  _slot_types = ['std_msgs/Header','uint32','uint16','uint8','pulson_ros/RangeNetNDBEntry[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,host_node,message_id,number_of_neighbor_entries,database

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RangeNetNDB, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.host_node is None:
        self.host_node = 0
      if self.message_id is None:
        self.message_id = 0
      if self.number_of_neighbor_entries is None:
        self.number_of_neighbor_entries = 0
      if self.database is None:
        self.database = []
    else:
      self.header = std_msgs.msg.Header()
      self.host_node = 0
      self.message_id = 0
      self.number_of_neighbor_entries = 0
      self.database = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_IHB().pack(_x.host_node, _x.message_id, _x.number_of_neighbor_entries))
      length = len(self.database)
      buff.write(_struct_I.pack(length))
      for val1 in self.database:
        _x = val1
        buff.write(_get_struct_I2BHI2H2B4I().pack(_x.node_id, _x.range_status, _x.antenna_mode, _x.stopwatch_time, _x.range, _x.range_error, _x.range_velocity, _x.range_measurement_type, _x.flags, _x.stats_age_ms, _x.range_update_timestamp_ms, _x.last_heard_timestamp_ms, _x.added_to_ndb_timestamp_ms))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.database is None:
        self.database = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.host_node, _x.message_id, _x.number_of_neighbor_entries,) = _get_struct_IHB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.database = []
      for i in range(0, length):
        val1 = pulson_ros.msg.RangeNetNDBEntry()
        _x = val1
        start = end
        end += 34
        (_x.node_id, _x.range_status, _x.antenna_mode, _x.stopwatch_time, _x.range, _x.range_error, _x.range_velocity, _x.range_measurement_type, _x.flags, _x.stats_age_ms, _x.range_update_timestamp_ms, _x.last_heard_timestamp_ms, _x.added_to_ndb_timestamp_ms,) = _get_struct_I2BHI2H2B4I().unpack(str[start:end])
        self.database.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_IHB().pack(_x.host_node, _x.message_id, _x.number_of_neighbor_entries))
      length = len(self.database)
      buff.write(_struct_I.pack(length))
      for val1 in self.database:
        _x = val1
        buff.write(_get_struct_I2BHI2H2B4I().pack(_x.node_id, _x.range_status, _x.antenna_mode, _x.stopwatch_time, _x.range, _x.range_error, _x.range_velocity, _x.range_measurement_type, _x.flags, _x.stats_age_ms, _x.range_update_timestamp_ms, _x.last_heard_timestamp_ms, _x.added_to_ndb_timestamp_ms))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.database is None:
        self.database = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 7
      (_x.host_node, _x.message_id, _x.number_of_neighbor_entries,) = _get_struct_IHB().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.database = []
      for i in range(0, length):
        val1 = pulson_ros.msg.RangeNetNDBEntry()
        _x = val1
        start = end
        end += 34
        (_x.node_id, _x.range_status, _x.antenna_mode, _x.stopwatch_time, _x.range, _x.range_error, _x.range_velocity, _x.range_measurement_type, _x.flags, _x.stats_age_ms, _x.range_update_timestamp_ms, _x.last_heard_timestamp_ms, _x.added_to_ndb_timestamp_ms,) = _get_struct_I2BHI2H2B4I().unpack(str[start:end])
        self.database.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_IHB = None
def _get_struct_IHB():
    global _struct_IHB
    if _struct_IHB is None:
        _struct_IHB = struct.Struct("<IHB")
    return _struct_IHB
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_I2BHI2H2B4I = None
def _get_struct_I2BHI2H2B4I():
    global _struct_I2BHI2H2B4I
    if _struct_I2BHI2H2B4I is None:
        _struct_I2BHI2H2B4I = struct.Struct("<I2BHI2H2B4I")
    return _struct_I2BHI2H2B4I
